repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.6.0
  hooks:
  - id: python-check-blanket-noqa
- repo: https://github.com/timothycrosley/isort
  rev: 5.5.3
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
